#!/bin/sh
LC_ALL=C
export LC_ALL

sed \
-e 's/æ/^c/g' -e 's/Æ/^C/g' \
-e 's/ø/^g/g' -e 's/Ø/^G/g' \
-e 's/¶/^h/g' -e 's/¦/^H/g' \
-e 's/¼/^j/g' -e 's/¬/^J/g' \
-e 's/þ/^s/g' -e 's/Þ/^S/g' \
-e 's/ý/^u/g' -e 's/Ý/^U/g' \
-e "s/á/\\\'a/g" -e 's/ç/\\c{c}/g' \
-e "s/é/\\\'e/g" -e 's/ü/\\\"u/g' \
-e "s/´/^'/g"

# Local variables:
# coding: latin-3
# End:
