#!/bin/sh
LC_ALL=C
export LC_ALL

sed \
-e 's/æ/^c/g; s/Æ/^C/g' \
-e 's/ø/^g/g; s/Ø/^G/g' \
-e 's/¶/^h/g; s/¦/^H/g' \
-e 's/¼/^j/g; s/¬/^J/g' \
-e 's/þ/^s/g; s/Þ/^S/g' \
-e 's/ý/^u/g; s/Ý/^U/g' \
-e "s/á/\\\'a/g" -e 's/ç/\\c{c}/g' \
-e "s/é/\\\'e/g" -e 's/ü/\\\"u/g; s/ö/\\\"o/g' \
-e "s/´/^'/g"

# Local variables:
# coding: latin-3
# End:
