#!/bin/bash
# -*- coding: utf-8 -*-

iconv -f ISO-8859-3 -t UTF-8 ../src/vortoj.l3 |\
sed -Ee 's:\{\\o\}:ø:g; s~(/.*)\\~\1÷~; s/coding:latin-3/coding:utf-8/' \
    -e 's%(/[[:graph:]]+)(.*)([[:space:]]*#mav|[[:space:]]*#arhx)\>%\1!\2%' \
    -e 's%^(=?[[:alpha:]]*[[:space:]]+[-ʼ[:alpha:]]+)\>([[:space:]].*)(#mav)\>%\1/!\2%' \
    -e 's%(/[[:graph:]]+)(.*)([[:space:]]*#rar)\>%\1?\2%' \
    -e 's%^([=[:alpha:]].+/[^[:space:]]+)(.*)(#rar)\b%\1?\2%' > eoootmp1
#    -e 's%^(=?[[:alpha:]]*[[:space:]]+[-ʼ[:alpha:]]+)\>([[:space:]].*)(#rar)\>%\1/?\2%' > eoootmp1

#FILTER=`echo $1 | sed -e 's/\<\([a-zA-Z]*\)\>,*/s,\#\1,,;/g'`

# $FILTER estas sed-tasko por malmarki linion entenatan ajnan el la
# menditaj sxlosiloj; ekz-e por "komp,etn,Eujo,pers,mll,pok,var,drv"
# $FILTER estas
# /#komp/s,#.*,,;/#etn/s,#.*,,;/#Eujo/s,#.*,,;/#pers/s,#.*,,;\
# /#mll/s,#.*,,;/#pok/s,#.*,,;/#var/s,#.*,,;/#drv/s,#.*,,;

FILTER=`echo $1, | sed -e 's|\([.a-zA-Z]*\),|/\#\1/s%#.*$%%;|g'`
echo "FILTER == $FILTER"

# case `expr $3 : '\([a-z]\).*'` in
#     'a') APO="s/´/'/g"
#          ;;
#     'q') APO="s/´/’/g"
#          ;;
#     'u') APO="s/´/ʼ/g"
#          ;;
#     *) echo "Wrong APO"; exit 1
#        ;;
# esac
if [ `expr index $3 "u"` -gt 0 ]
then APO="s/´/ʼ/g"
elif [ `expr index $3 "q"` -gt 0 ]
then APO="s/´/’/g"
elif [ `expr index $3 "a"` -gt 0 ]
then APO="s/´/'/g"
else echo "Wrong APO"; exit 1
fi
echo "APO == $APO"

sed -e "s/##.*$//; $FILTER; /\#/d; $APO" eoootmp1 > eoootmp2
../tools/plusminus.sed < eoootmp2 | tr '%' '\n' | sort -uf > $2

# cat eoootmp2 | sed -e 's/^\([^=][^ 	]*\)-[ 	]*\(^\)*\([^+-]*\)$/&\
# \1\2\l\3/;
# s/^\([^=][^ 	]*\)-[ 	]*\(^\)*\([^-]*\)-\([^+]*\)$/\1-\2\3\4\
# \1\2\l\3/;
# s/^\([^=][^ 	]*\)-[ 	]*\(^\)*\([^+]*\)+\([^-]*\)$/\1-\2\3\
# \1\2\l\3\4/;
# s/^\([^=][^ 	]*\)-[ 	]*\(^\)*\([^-]*\)-\([^+]*\)+\(.*\)$/\1-\2\3\4\
# \1\2\l\3\5/;
# s/[ =	]//g; /^[[:space:]]*$/d; 
# # tekstoprezent(ad)o:
# s/\([^(]*\)(\([^)]*\))\(.*\)$/\1\2\3\n\1\3/' | sort -uf > eoootmp3
