#!/bin/sh

# LC_ALL=C
# LC_CTYPE=C
# export LC_CTYPE LC_ALL

iconv -f ISO-8859-3 -t UTF-8 <../src/vortoj.l3 |\
sed -Ee 's:\{\\o\}:ø:g; s|´|’|g; s/coding:latin-3/coding:utf-8/' \
    -e 's%(/[[:graph:]]+)(.*)([[:space:]]*#mav|[[:space:]]*#arhx)\>%\1!\2%' \
    -e 's%^(=?[[:alpha:]]*[[:space:]]+[-’[:alpha:]]+)\>([[:space:]].*)(#mav)\>%\1/!\2%' \
    -e 's%(/[[:graph:]]+)(.*)([[:space:]]*#rar)\>%\1?\2%' \
    -e 's%^(=?[[:alpha:]]*[[:space:]]+[-’[:alpha:]]+)\>([[:space:]].*)(#rar)\>%\1/?\2%' \
    > eoootmp1


#FILTER=`echo $1 | sed -e 's/\<\([a-zA-Z]*\)\>,*/s,\#\1,,;/g'`

# $FILTER estas sed-tasko por malmarki linion entenatan ajnan el la
# menditaj sxlosiloj; ekz-e por "komp,etn,Eujo,pers,mll,pok,var,drv"
# $FILTER estas
# /#komp/s,#.*,,;/#etn/s,#.*,,;/#Eujo/s,#.*,,;/#pers/s,#.*,,;\
# /#mll/s,#.*,,;/#pok/s,#.*,,;/#var/s,#.*,,;/#drv/s,#.*,,;

FILTER=`echo $1, | sed -e 's|\([.a-zA-Z]*\),|/\#\1/s%#.*$%%;|g'`

echo "FILTER == $FILTER"

sed -e "s/#{[^}]*}//g; $FILTER; /\#/d" eoootmp1 > eoootmp2
cat eoootmp2 | sed -e 's/^\([^=][^ 	]*\)-[ 	]*\(^\)*\([^+-]*\)$/&\
\1\2\l\3/;
s/^\([^=][^ 	]*\)-[ 	]*\(^\)*\([^-]*\)-\([^+]*\)$/\1-\2\3\4\
\1\2\l\3/;
s/^\([^=][^ 	]*\)-[ 	]*\(^\)*\([^+]*\)+\([^-]*\)$/\1-\2\3\
\1\2\l\3\4/;
s/^\([^=][^ 	]*\)-[ 	]*\(^\)*\([^-]*\)-\([^+]*\)+\(.*\)$/\1-\2\3\4\
\1\2\l\3\5/;
s/[ =	]//g; /^[[:space:]]*$/d; 
# tekstoprezent(ad)o:
s/\([^(]*\)(\([^)]*\))\(.*\)$/\1\2\3\n\1\3/' | sort -uf > eoootmp3

wc -l eoootmp3 | sed -Ee 's/^ *([0-9]+)\>.*$/\1/' | cat - eoootmp3 > $2
