#!/bin/sh
set -e
set -x

LC_CTYPE=C
export LC_CTYPE
FILTER="$1"
KIEN=$2
if [ x$FILTER = xcxio ]; then
    YES="s%#\w+%%"
else
    YES=`echo "$FILTER" | tr ',' '|'`
    YES="s%#($YES)%%g"
fi
echo YES=$YES
# $YES estas sed-tasko por malmarki linion entenatan ajnan el la
# menditaj sxlosiloj; ekz-e por "komp,etn,Eujo,pers,mll,pok,var,drv"
# $YES estas "#(komp|etn|Eujo|pers|mll|pok|var|drv)"

sed -Ee 's/##.*//' -e $YES -e '/#/d' -e 's/[=[:blank:]]+//g' ../src/vortoj.l3 > tt.l3
    cat tt.l3 | ../tools/plusminus.sed > ttt.l3; cat ttt.l3 | tr '%' '\n' | ../tools/askiigu | sort -uf > $2

test -s $KIEN
